apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: lease-test
  name: lease-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lease-test
  template:
    metadata:
      labels:
        app: lease-test
    spec:
      containers:
        - name: lease-test
          imagePullPolicy: Never
          image: lease-kubernetes-int-test:latest
