addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.1")

addSbtPlugin("de.heikoseeberger"                 % "sbt-header"       % "5.0.0")
addSbtPlugin("com.geirsson"                      % "sbt-scalafmt"     % "0.4.10")
addSbtPlugin("com.dwijnand"                      % "sbt-dynver"       % "2.0.0")
addSbtPlugin("com.lightbend.paradox"             % "sbt-paradox"      % "0.4.3")
addSbtPlugin("com.eed3si9n"                      % "sbt-unidoc"       % "0.3.3")
addSbtPlugin("com.thoughtworks.sbt-api-mappings" % "sbt-api-mappings" % "1.0.0")
addSbtPlugin("org.foundweekends"                 % "sbt-bintray"      % "0.5.4")
addSbtPlugin("com.lightbend"                     % "sbt-whitesource"  % "0.1.14")
addSbtPlugin("com.typesafe.sbt"                  % "sbt-git"          % "0.9.3")
