name: Integration test for Kubernetes API with Maven

on:
  pull_request:
  push:
    branches:
      - main
      - release-*
    tags-ignore: [ v.* ]
    # Different than its sibilings, we don't configure this workflow to run as a cron job.

permissions:
  contents: read

jobs:
   integration-test:
    name: Integration Tests for Kubernetes API with Maven
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Set up JDK 11
        uses: coursier/setup-action@v1.3.0
        with:
          jvm: temurin:1.11.0

      - name: Setup Minikube
        # https://github.com/manusa/actions-setup-minikube/releases
        # v2.7.1
        uses: manusa/actions-setup-minikube@4582844dcacbf482729f8d7ef696f515d2141bb9
        with:
          minikube version: 'v1.32.0'
          kubernetes version: 'v1.28.4'
          driver: docker
          start args: '--addons=ingress'

      - name: Start docker
        run: |-
          ./integration-test/kubernetes-api-java/test.sh

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
