name: Integration test for Kubernetes API with Maven

on:
  pull_request:
  push:
    branches:
      - main
      - release-*
    tags-ignore: [ v.* ]
    # Different than its sibilings, we don't configure this workflow to run as a cron job.

permissions:
  contents: read

jobs:
   integration-test:
    name: Integration Tests for Kubernetes API with Maven
    runs-on: Akka-Default
    steps:
      - name: Checkout
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout GitHub merge
        if: github.event.pull_request
        run: |-
          git fetch origin pull/${{ github.event.pull_request.number }}/merge:scratch
          git checkout scratch

      - name: Cache Coursier cache
        # https://github.com/coursier/cache-action/releases
        uses: coursier/cache-action@v8.1.0

      - name: Set up JDK 11
        # https://github.com/coursier/setup-action/releases
        uses: coursier/setup-action@v3.0.0
        with:
          jvm: temurin:1.11.0

      - name: Run akka/github-actions-scripts
        uses: akka/github-actions-scripts/setup_global_resolver@main

      - name: Setup Minikube
        # https://github.com/manusa/actions-setup-minikube/releases
        uses: manusa/actions-setup-minikube@v2.16.1
        with:
          minikube version: 'v1.38.0'
          kubernetes version: 'v1.35.0'
          driver: docker
          start args: '--addons=ingress'

      - name: Start docker
        run: |-
          ./integration-test/kubernetes-api-java/test.sh

      - name: Print logs on failure
        if: ${{ failure() }}
        run: find . -name "*.log" -exec ./scripts/cat-log.sh {} \;
